# config.yml

backend:
    name: github
    repo: rasoulghaznavi/blog # Path to your GitHub repository
  media_folder: 'assets/uploads'
  collections:
    - name: 'blog'
      label: 'Blog'
      folder: '_posts/'
      fields:
        - { name: Rasoul's Blog }